Use set_default when storing credentials
Storing non-default credentials into default ccache is not supported and
causes errors like this:
gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2249944339): Storing of non-default credentials is not supported by the mechanism